@echo ""
@echo "SMC Version Check:-"
smcutil.efi -v
@echo ""
@echo "Thanks to Paul L Daniels, Logi.wiki,"
@echo "EineWildeStehlampe, theSmudge, NRGZ,"
@echo "Nobluesky."
@echo ""
@echo "Process complete:"
@echo "Type 'reset -w' to reboot, 'reset -s' to power off."