@echo ""
@echo "Mac Mini SMC Firmware Menu"
@echo "Type your board number, then press enter:-"
@echo ""
@echo " A1347 820-5509 - FW: 2.24f32 - Type: 820-5509.nsh"
@echo ""
@echo "Type 'startup.nsh', the press enter to go back."
@echo ""
@echo "NOTE: Script will run immediately, so be sure"
@echo "      when you choose to run the script."
@echo ""