@echo ""
@echo "SMCTool V1.1.0 by David R (Muerto)"
@echo "Make sure the device is plugged in!"
@echo ""
@echo "Type your platform, then press enter:-"
@echo ""
@echo " MacBook Menu   -  Type: macbook.nsh"
@echo " Mac Mini Menu  -  Type: macmini.nsh"
@echo " iMac  Menu     -  Type: imac.nsh"
@echo ""
@echo "Type 'exit', then press enter to leave the shell."
@echo ""